---
# This playbook deploys the spring demo application onto a set of servers

# Apply common configuration to all hosts
- hosts: all

  roles:
  - common

# Apply jboss configuration to app servers
- hosts: appservers
  
  roles:
  - jboss

# Deploy WAR file to app servers
- hosts: appservers
  
  tasks:
    - name: deploy war file
      get_url:
        url: http://jenkins.rdu.salab.redhat.com:8080/job/spring-webapp-demo/lastSuccessfulBuild/artifact/target/spring-webapp.war
        dest: /opt/jboss-eap-7.0/standalone/deployments/spring-webapp.war

# Apply load balancer configuration to load balancers
- hosts: lbservers
  
  roles:
  - haproxy
